
#' @title Calculates Summary Statistics
#' @encoding UTF-8
#' @description Here is a sample function.
#' @details
#' Some details about the sample function.
#' @param data The input data frame for which calculate summary statistics.
#' @param by An optional by group.
#' @param class The variable or variables to perform frequency counts on.
#' @param class_options The option specifications for the table parameter.
#' @param var The variable(s) to calculate summary statistics for.
#' @param weight An optional weight parameter.
#' @param weight_options The option specifications for the weight parameter.
#' @param output The directory path or libname to output data generated by
#' the \code{proc_freq} function.
#' @param view Whether to display the report
#' @param report_type The output type for any report output.  Valid values are
#' 'HTML', 'TXT', 'PDF', 'RTF', 'DOCX'.  Multiple outputs can be
#' requested by passing a vector of output types.  If the report_location parameter
#' is specified, the outputs will be written to that location.  Otherwise,
#' they will be written to a temp directory.  The default value is NULL.
#' @param report_location A path to write any report output requested by
#' the print parameter. The path may be either a full path with file name,
#' or a directory name.  If the file name is not specified, the procedure
#' type will be used.  If no path is specified, files will be
#' written to a temp directory.  Default is NULL.
#' @param titles A vector of one or more titles to use for the report output.
#' @param digits The number of digits to round statistics produced
#' by the function.
#' @return A list of data frames that contain the requested frequency tables.
#' @import fmtr
#' @export
proc_means <- function(data,
                      by = NULL,
                      class = NULL,
                      class_options = NULL,
                      var = NULL,
                      weight = NULL,
                      weight_options = NULL,
                      view = TRUE,
                      output = NULL,
                      report_type = NULL,
                      report_location = NULL,
                      titles = NULL,
                      digits = 4) {


}



