

#' @title Generates Frequency Statistics
#' @encoding UTF-8
#' @description Here is a sample function.
#' @details
#' Some details about the sample function.
#' @param data The input data frame to perform frequency calculations on.
#' @param by An optional by group.
#' @param tables The variable or variables to perform frequency counts on.
#' @param table_options The option specifications for the table parameter.
#' @param weight An optional weight parameter.
#' @param weight_options The option specifications for the weight parameter.
#' @param output The directory path or libname to output data generated by
#' the \code{proc_freq} function.
#' @param view Whether to display procedure results in the viewer.  Valid values
#' are TRUE and FALSE.  Default is TRUE.
#' @param report_type The output type for any report output.  Valid values are
#' 'HTML', 'TXT', 'PDF', 'RTF', 'DOCX'.  Multiple outputs can be
#' requested by passing a vector of output types.  If the report_location parameter
#' is specified, the outputs will be written to that location.  Otherwise,
#' they will be written to a temp directory.  The default value is NULL.
#' @param report_location A path to write any report output requested by
#' the print parameter. The path may be either a full path with file name,
#' or a directory name.  If the file name is not specified, the procedure
#' type will be used.  If no path is specified, files will be
#' written to a temp directory.  Default is NULL.
#' @param titles A vector of one or more titles to use for the report output.
#' @param digits The number of digits to round statistics produced
#' by the function.
#' @return A list of data frames that contain the requested frequency tables.
#' The list item names are specified in the \code{tables} parameter.
#' @import fmtr
#' @export
proc_freq <- function(data,
                      by = NULL,
                      tables = NULL,
                      table_options = NULL,
                      weight = NULL,
                      weight_options = NULL,
                      view = TRUE,
                      output = NULL,
                      report_type = NULL,
                      report_location = NULL,
                      titles = NULL,
                      digits = 4) {

  res <- list()
  # print("Orig print_location")
  # print(print_location)

  for (i in seq_len(length(tables))) {

    nm <- names(tables)[i]
    tb <- tables[i]

    crstab <- NULL

    splt <- trimws(strsplit(tb, "*", fixed = TRUE)[[1]])

    if (length(splt) == 1) {

      result <- freq_oneway(data, tb, weight, digits)
    } else if (length(splt) == 2) {

      result <- freq_twoway(data, splt[1], splt[2], weight, digits)

      #crstab <- cross_tab(result)

    } else {


    }

    if (is.null(nm))
      res[[tb]] <- result
    else if (nchar(nm) == 0)
      res[[tb]] <- result
    else
      res[[nm]] <- result

    if (!is.null(crstab)) {

      res[[length(res) + 1]] <- crstab
    }


  }

  if (!is.null(output)) {

    if (all(class(output) == "character")) {


    } else if (class(output) %in% c("lib")) {

      for (dt in names(res)) {

        #lib_add(output
      }

    }

  }

  if (!is.null(report_type)) {

    loc <- get_location("freq", report_location)
    out <- output_report(res, proc_type = 'freq', dir_name = loc["dir_name"],
                         file_name = loc["file_name"], out_type = report_type,
                         titles = titles)


  }

  if (view == TRUE) {


    vrfl <- tempfile()

    out <- output_report(res, proc_type = 'freq', dir_name = dirname(vrfl),
                         file_name = basename(vrfl), out_type = "HTML",
                         titles = titles)

    show_viewer(out)
  }

  return(res)

}


#' @import fmtr
#' @noRd
freq_oneway <- function(data, tb, weight, digits) {

  var <- data[[tb]]

  if (is.null(weight)) {

    categories <- names(sort(table(var)))
    frequencies <- as.vector(sort(table(var)))

  } else {

    cnts <- aggregate(data[[weight]], list(data[[tb]]), FUN = sum)
    categories <- cnts$Group.1
    frequencies <- cnts$x
  }

  n <- sum(frequencies)
  percentages <- frequencies / n * 100
  cum_frequencies <- cumsum(frequencies)
  cum_percentages <- cumsum(percentages)


  result <- data.frame("Category" = categories,
                       "Frequency" = frequencies,
                       "Percentage" = percentages,
                       "Cum_Freq" = cum_frequencies,
                       "Cum_Pct" = cum_percentages,
                       stringsAsFactors = FALSE)



  lbl <- attr(data[[tb]], "label")

  if (is.null(lbl))
    lbl <- tb


  labels(result) <- c(Category = lbl,
                      Cum_Freq = "Cumulative Frequency",
                      Cum_Pct = "Cumulative Percentage")

  fmt <- paste0("%.", digits, "f")

  formats(result) <- list(Cum_Pct = fmt,
                          Percentage = fmt)


  return(result)
}


#' @import fmtr
#' @noRd
freq_twoway <- function(data, tb1, tb2, weight, digits) {


  data[["__cnt"]] <- 1
  v1 <- data[[tb1]]
  v2 <- data[[tb2]]

  t1 <- names(sort(table(v1)))
  t2 <- names(sort(table(v2)))
  ex <- expand.grid(tb1 = t1, tb2 = t2, stringsAsFactors = FALSE)
  ex[["__cnt"]] <- 0

  if (is.null(weight)) {

    c1 <- data[["__cnt"]]

  } else {

    c1 <-data[[weight]]

  }

  c1 <- append(c1, ex[["__cnt"]])
  v1 <- append(v1, ex[["tb1"]])
  v2 <- append(v2, ex[["tb2"]])

  cnts <- aggregate(c1, list(v1, v2), FUN = sum)
  categories1 <- cnts$Group.1
  categories2 <- cnts$Group.2
  frequencies <- cnts$x

  n <- sum(frequencies)
  percentages <- frequencies / n * 100


  result <- data.frame("Category1" = categories1,
                       "Category2" = categories2,
                       "Frequency" = frequencies,
                       "Percentage" = percentages,
                       stringsAsFactors = FALSE)


  result <- result[order(result$Category1, result$Category2), ]

  lbl1 <- attr(data[[tb1]], "label")
  lbl2 <- attr(data[[tb2]], "label")

  if (is.null(lbl1))
    lbl1 <- tb1
  if (is.null(lbl2))
    lbl2 <- tb2

  labels(result) <- c(Category1 = lbl1,
                      Category2 = lbl2)

  formats(result) <- list(Percentage = paste0("%.", digits, "f"))


  return(result)

}

